-- Velvet River Poker Demo
-- Structure-only schema for planning and presentation.
-- Review every field, index, and foreign key before using in production.

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(80) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `tables` (
  table_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  game_type VARCHAR(50) NOT NULL,
  blinds VARCHAR(50) NOT NULL,
  max_players TINYINT UNSIGNED NOT NULL DEFAULT 6,
  status VARCHAR(30) NOT NULL DEFAULT 'open',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS players (
  player_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  table_id INT UNSIGNED NULL,
  username VARCHAR(80) NOT NULL,
  chip_balance DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  seat_number TINYINT UNSIGNED NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_players_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_players_table FOREIGN KEY (table_id) REFERENCES `tables` (table_id)
);

CREATE TABLE IF NOT EXISTS hands (
  hand_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  table_id INT UNSIGNED NOT NULL,
  board_cards VARCHAR(120) NULL,
  hand_status VARCHAR(30) NOT NULL DEFAULT 'completed',
  started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP NULL DEFAULT NULL,
  CONSTRAINT fk_hands_table FOREIGN KEY (table_id) REFERENCES `tables` (table_id)
);

CREATE TABLE IF NOT EXISTS bets (
  bet_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  hand_id BIGINT UNSIGNED NOT NULL,
  player_id INT UNSIGNED NOT NULL,
  amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  street VARCHAR(20) NOT NULL DEFAULT 'preflop',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_bets_hand FOREIGN KEY (hand_id) REFERENCES hands (hand_id),
  CONSTRAINT fk_bets_player FOREIGN KEY (player_id) REFERENCES players (player_id)
);

CREATE TABLE IF NOT EXISTS pots (
  pot_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  hand_id BIGINT UNSIGNED NOT NULL,
  total_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  pot_type VARCHAR(30) NOT NULL DEFAULT 'main',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_pots_hand FOREIGN KEY (hand_id) REFERENCES hands (hand_id)
);

CREATE TABLE IF NOT EXISTS rake (
  rake_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  hand_id BIGINT UNSIGNED NOT NULL,
  rake_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_rake_hand FOREIGN KEY (hand_id) REFERENCES hands (hand_id)
);

CREATE TABLE IF NOT EXISTS chip_requests (
  request_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  player_id INT UNSIGNED NOT NULL,
  amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  status VARCHAR(30) NOT NULL DEFAULT 'pending',
  requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  reviewed_at TIMESTAMP NULL DEFAULT NULL,
  CONSTRAINT fk_chip_requests_player FOREIGN KEY (player_id) REFERENCES players (player_id)
);

CREATE TABLE IF NOT EXISTS chip_transactions (
  transaction_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  player_id INT UNSIGNED NOT NULL,
  amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  action VARCHAR(40) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_chip_transactions_player FOREIGN KEY (player_id) REFERENCES players (player_id)
);

CREATE TABLE IF NOT EXISTS hand_history (
  history_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  hand_id BIGINT UNSIGNED NOT NULL,
  full_hand_logs LONGTEXT NOT NULL,
  recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_hand_history_hand FOREIGN KEY (hand_id) REFERENCES hands (hand_id)
);

CREATE TABLE IF NOT EXISTS player_stats (
  stat_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  player_id INT UNSIGNED NOT NULL,
  wins INT UNSIGNED NOT NULL DEFAULT 0,
  losses INT UNSIGNED NOT NULL DEFAULT 0,
  hands_played INT UNSIGNED NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_player_stats_player FOREIGN KEY (player_id) REFERENCES players (player_id)
);
